{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-guava",
    "version": "2.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "25.1-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.16.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.16.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.16.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-guava-2.16.2.jar",
          "url": "jackson-datatype-guava-2.16.2.jar",
          "size": 98265,
          "sha512": "9ae912e43044f445f498bd5736f842419ed94db7dac66fd39f5c225f8651c05b89f8e705f412c56596b7bdf37b7627e24c445b2b1350e7e29ae4c630ffe78e8b",
          "sha256": "abb26287e3a6a0b0103a102828687033735da4302feef5108871b663584aaab0",
          "sha1": "d8722b2efac531099b0b69ceb9c4886dd3216e32",
          "md5": "3eb45e0a5b0aa6a51e868c3190c232e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "25.1-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.16.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.16.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.16.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-guava-2.16.2.jar",
          "url": "jackson-datatype-guava-2.16.2.jar",
          "size": 98265,
          "sha512": "9ae912e43044f445f498bd5736f842419ed94db7dac66fd39f5c225f8651c05b89f8e705f412c56596b7bdf37b7627e24c445b2b1350e7e29ae4c630ffe78e8b",
          "sha256": "abb26287e3a6a0b0103a102828687033735da4302feef5108871b663584aaab0",
          "sha1": "d8722b2efac531099b0b69ceb9c4886dd3216e32",
          "md5": "3eb45e0a5b0aa6a51e868c3190c232e9"
        }
      ]
    }
  ]
}
