{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-websocket",
    "version": "6.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-websocket-6.1.10.jar",
          "url": "spring-websocket-6.1.10.jar",
          "size": 443651,
          "sha512": "9c6e567c62e178178b1b59949d4544d998811e6530d09e1329dc0d18e0ade5b30fe9e598e2bbf605cd9ab677343208757e5558f605fc2466536c20a33d963be1",
          "sha256": "8383b7105cb157193cf87f6ea2b1050867236acf5ac49442425d9df7ed539513",
          "sha1": "448ee505c11b87dd4732d27092f932b47feaf912",
          "md5": "dd9f3224e4957b16661997373f49a369"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-websocket-6.1.10.jar",
          "url": "spring-websocket-6.1.10.jar",
          "size": 443651,
          "sha512": "9c6e567c62e178178b1b59949d4544d998811e6530d09e1329dc0d18e0ade5b30fe9e598e2bbf605cd9ab677343208757e5558f605fc2466536c20a33d963be1",
          "sha256": "8383b7105cb157193cf87f6ea2b1050867236acf5ac49442425d9df7ed539513",
          "sha1": "448ee505c11b87dd4732d27092f932b47feaf912",
          "md5": "dd9f3224e4957b16661997373f49a369"
        }
      ]
    }
  ]
}
