{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.ben-manes",
    "module": "gradle-versions-plugin",
    "version": "0.51.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-versions-plugin-0.51.0.jar",
          "url": "gradle-versions-plugin-0.51.0.jar",
          "size": 168440,
          "sha512": "9305567d8782f4783cd7d5cd23eaf3e6be1b63e7f7e0b6bd113ff8e65628140da7200bb81c3db3372fa699f468042d7a0016efbdca851d5cb774f67359cb2f5b",
          "sha256": "843149e32b9176621ccf7f1db4438408c5a9f9b58cd57210537d9b738054021e",
          "sha1": "33ddbcb80435d26e6bd295cf88ff962f6be5eaa5",
          "md5": "71cd4ac09716d50c12ab8e672f458331"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.20"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-versions-plugin-0.51.0.jar",
          "url": "gradle-versions-plugin-0.51.0.jar",
          "size": 168440,
          "sha512": "9305567d8782f4783cd7d5cd23eaf3e6be1b63e7f7e0b6bd113ff8e65628140da7200bb81c3db3372fa699f468042d7a0016efbdca851d5cb774f67359cb2f5b",
          "sha256": "843149e32b9176621ccf7f1db4438408c5a9f9b58cd57210537d9b738054021e",
          "sha1": "33ddbcb80435d26e6bd295cf88ff962f6be5eaa5",
          "md5": "71cd4ac09716d50c12ab8e672f458331"
        }
      ]
    }
  ]
}
