{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-jaxb-annotations",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jaxb-annotations-2.17.1.jar",
          "url": "jackson-module-jaxb-annotations-2.17.1.jar",
          "size": 36125,
          "sha512": "d09bef0f7a3c3f21377f740c5514be7aa4e674b0d852169332dbe2b49a81858d9c3d11ca88039f9f0c80ca1205f1e48b99557671659ae55f90d765b077c733ad",
          "sha256": "f59e997b3fb9e6df2dad1ded020d1c08ff3412a53506fa1e616d143a95c451ce",
          "sha1": "19be34b80ab486f7dde39e9310fd533193f681a5",
          "md5": "4e7a2b02fc2c4d4b8c6132db45d55403"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jaxb-annotations-2.17.1.jar",
          "url": "jackson-module-jaxb-annotations-2.17.1.jar",
          "size": 36125,
          "sha512": "d09bef0f7a3c3f21377f740c5514be7aa4e674b0d852169332dbe2b49a81858d9c3d11ca88039f9f0c80ca1205f1e48b99557671659ae55f90d765b077c733ad",
          "sha256": "f59e997b3fb9e6df2dad1ded020d1c08ff3412a53506fa1e616d143a95c451ce",
          "sha1": "19be34b80ab486f7dde39e9310fd533193f681a5",
          "md5": "4e7a2b02fc2c4d4b8c6132db45d55403"
        }
      ]
    }
  ]
}
