{
  "formatVersion": "1.1",
  "component": {
    "group": "org.openapitools",
    "module": "openapi-generator-gradle-plugin",
    "version": "7.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "openapi-generator-gradle-plugin-7.6.0.jar",
          "url": "openapi-generator-gradle-plugin-7.6.0.jar",
          "size": 105774,
          "sha512": "6b86dfcbe82e7e08a3e2956e57076943ed4333d7c215befc03b11ed40da42c13dd1a4f0a5c1888261054145f752a36f5fcdcbc1cf6630e555eaedef4c154133e",
          "sha256": "8508153134b370557644cc156e70f8a93449a094a0fd235ae368a52538da57c5",
          "sha1": "8e42c1e7d5bc80d2592bd7f23ec5d90a714a85c2",
          "md5": "e6079753222f71a24b8e1e22bb88a94a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.openapitools",
          "module": "openapi-generator",
          "version": {
            "requires": "7.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "openapi-generator-gradle-plugin-7.6.0.jar",
          "url": "openapi-generator-gradle-plugin-7.6.0.jar",
          "size": 105774,
          "sha512": "6b86dfcbe82e7e08a3e2956e57076943ed4333d7c215befc03b11ed40da42c13dd1a4f0a5c1888261054145f752a36f5fcdcbc1cf6630e555eaedef4c154133e",
          "sha256": "8508153134b370557644cc156e70f8a93449a094a0fd235ae368a52538da57c5",
          "sha1": "8e42c1e7d5bc80d2592bd7f23ec5d90a714a85c2",
          "md5": "e6079753222f71a24b8e1e22bb88a94a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openapi-generator-gradle-plugin-7.6.0-sources.jar",
          "url": "openapi-generator-gradle-plugin-7.6.0-sources.jar",
          "size": 21272,
          "sha512": "05dca9e06f20955b439bb0c418b5199d21b7e0925ae53ce304ac04697e37487dc962871149de32442b704cc4e576911b9204f1cc9bb2e856a7129e89d3027dcd",
          "sha256": "cd0b52ea4dab06d1261380373b9bcfbec3a2f9dbd1e24829dd72a940818f78e7",
          "sha1": "925b49c6a2dc60a703fc0d69d4e56ff9c5012b39",
          "md5": "673709cd90f4853990ad72a2b3724053"
        },
        {
          "name": "openapi-generator-gradle-plugin-7.6.0-sources.jar",
          "url": "openapi-generator-gradle-plugin-7.6.0-sources.jar",
          "size": 21272,
          "sha512": "05dca9e06f20955b439bb0c418b5199d21b7e0925ae53ce304ac04697e37487dc962871149de32442b704cc4e576911b9204f1cc9bb2e856a7129e89d3027dcd",
          "sha256": "cd0b52ea4dab06d1261380373b9bcfbec3a2f9dbd1e24829dd72a940818f78e7",
          "sha1": "925b49c6a2dc60a703fc0d69d4e56ff9c5012b39",
          "md5": "673709cd90f4853990ad72a2b3724053"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openapi-generator-gradle-plugin-7.6.0-javadoc.jar",
          "url": "openapi-generator-gradle-plugin-7.6.0-javadoc.jar",
          "size": 261,
          "sha512": "7eeab55e3ef6ae97b95652be4217bc035fb6496030d7d2b35d9bb9ef4fa4abfb37bc9ba8820aaffdb8d55bb9da7ef8d899eb4d1ca7259cf5f4eb6eba2dddbb1c",
          "sha256": "7837e659084ac9445bd140f6e1842b5b44fc75c2f75f433560ab0de6b4e3dc4e",
          "sha1": "dbd1b6ce3a65a3fafdf1cd21fb45cab0568ec9b6",
          "md5": "9e57be733e6094c3504ce01019de76cf"
        },
        {
          "name": "openapi-generator-gradle-plugin-7.6.0-javadoc.jar",
          "url": "openapi-generator-gradle-plugin-7.6.0-javadoc.jar",
          "size": 261,
          "sha512": "7eeab55e3ef6ae97b95652be4217bc035fb6496030d7d2b35d9bb9ef4fa4abfb37bc9ba8820aaffdb8d55bb9da7ef8d899eb4d1ca7259cf5f4eb6eba2dddbb1c",
          "sha256": "7837e659084ac9445bd140f6e1842b5b44fc75c2f75f433560ab0de6b4e3dc4e",
          "sha1": "dbd1b6ce3a65a3fafdf1cd21fb45cab0568ec9b6",
          "md5": "9e57be733e6094c3504ce01019de76cf"
        }
      ]
    }
  ]
}
