{
  "formatVersion": "1.1",
  "component": {
    "group": "org.freemarker",
    "module": "freemarker",
    "version": "2.3.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "freemarker-2.3.33.jar",
          "url": "freemarker-2.3.33.jar",
          "size": 1877365,
          "sha512": "38c604d4d837b4089be9540fd11792a58e21ffa170fa9875e09cb55ab2c2131f50c41fb12f5268393b0a40f977775325b6eadc61432ea75392b8b763b72a8987",
          "sha256": "ab829182363e747a1530a368436242f4cca7ff309dd29bfca638a1fdc7b6771d",
          "sha1": "fecaeb606993fc9fd0f95fe5a644048a69c39474",
          "md5": "4ec135628fd640a201c1d4f8670cc020"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "freemarker-2.3.33.jar",
          "url": "freemarker-2.3.33.jar",
          "size": 1877365,
          "sha512": "38c604d4d837b4089be9540fd11792a58e21ffa170fa9875e09cb55ab2c2131f50c41fb12f5268393b0a40f977775325b6eadc61432ea75392b8b763b72a8987",
          "sha256": "ab829182363e747a1530a368436242f4cca7ff309dd29bfca638a1fdc7b6771d",
          "sha1": "fecaeb606993fc9fd0f95fe5a644048a69c39474",
          "md5": "4ec135628fd640a201c1d4f8670cc020"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "freemarker-2.3.33-sources.jar",
          "url": "freemarker-2.3.33-sources.jar",
          "size": 1434286,
          "sha512": "1d42dba1138e7714600443f9a982fd46dc609b74549bd89e385df8d360bd15c45d1ab23f3bea86632c62c1a8c516be6d5a6e07d60a0a26515a3acb81feaacd6a",
          "sha256": "e83bb30b32bae02ce1fff6e7f17c994119d0dcbf45ed579dc1b5a6e690f3dc96",
          "sha1": "4fbb000c2ed4794bc4799735ce0dc9e920396c28",
          "md5": "7402e24a2ffa0c173ba130f3745785cc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "freemarker-2.3.33-javadoc.jar",
          "url": "freemarker-2.3.33-javadoc.jar",
          "size": 1740530,
          "sha512": "c92de1662f6ac8c9a5a47063fdadcea5fcd0cc9fbd1b0c6f8b0361291fa2e10e5b3406c7df86370a7868ebdb7786218be2bd9e1e87b2545687f21108a74d7222",
          "sha256": "36d9d8db99741c747acd61697f0b43924f4adaf28c1ceaf108f49436e864001a",
          "sha1": "588c733bb44aeb3d4a6307b4a38d70bd9689085e",
          "md5": "018d9b4c2e2fc555dc970f61b78e372e"
        }
      ]
    }
  ]
}
