{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-guava",
    "version": "2.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "25.1-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-guava-2.17.0.jar",
          "url": "jackson-datatype-guava-2.17.0.jar",
          "size": 102656,
          "sha512": "738cd7c5cfb275f69efc13a2f4a196166fc6e7abd70d42b8c4ef43d2990a55283de772e27715257c74eef4b2d3ab2c5795ee6a0c6004895a892c3620d328bc8e",
          "sha256": "920f5db3a1671dd4d57aaefb75b3335cfbef364a0b8c0cb46902bb215a4d6417",
          "sha1": "a098cde82ed699af0cad0f5e01ae7130c1b9fbb3",
          "md5": "d191be347d07815dc9c25780114f0483"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "25.1-jre"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-guava-2.17.0.jar",
          "url": "jackson-datatype-guava-2.17.0.jar",
          "size": 102656,
          "sha512": "738cd7c5cfb275f69efc13a2f4a196166fc6e7abd70d42b8c4ef43d2990a55283de772e27715257c74eef4b2d3ab2c5795ee6a0c6004895a892c3620d328bc8e",
          "sha256": "920f5db3a1671dd4d57aaefb75b3335cfbef364a0b8c0cb46902bb215a4d6417",
          "sha1": "a098cde82ed699af0cad0f5e01ae7130c1b9fbb3",
          "md5": "d191be347d07815dc9c25780114f0483"
        }
      ]
    }
  ]
}
