name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  NODE_VERSION: "20.13.1"
  IMAGE_NAME: sunhao111555/allure-server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      ## Build prepare ##
      - name: Fast checkout
        uses: actions/checkout@v4
      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      ## Build Image ##
      - name: Build with Gradle
        run: ./gradlew --no-daemon -Pversion=${{ env.RELEASE_VERSION }} --stacktrace bootJar

      ## Release in DockerHub ##
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sunhao111555
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}

      ## Release in GitHub ##
      - name: Create GitHub release and upload jar
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.RELEASE_VERSION }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: build/libs/allure-server-${{ env.RELEASE_VERSION }}.jar
          draft: false
          prerelease: false
